[project]
name = "ml-be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.119.1",
    "tensorflow>=2.20.0",
    "uvicorn[standard]>=0.38.0",
]
